# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the gitlab_server VM
  config.vm.define "gitlab_server" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "generic/rocky8"
    # Specify the VM ip address
    config.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.network "private_network", ip: "192.168.121.240"
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "gitlab.server.local"
      # VM RAM in MB
      vb.memory = 4096
      # VM CPUs
      vb.cpus = 2
    end
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "4096"
      vmware.vmx["numvcpus"] = "2"
    end

  end

  # Use Vagrant Ansible provisioner : ansible_local allows executing ansible-playbook directly on the guest machine.
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "playbooks/run.yml"
    # Sync the vagrant folder on host machine to guest machine
    config.vm.synced_folder ".", "/vagrant"
    # Only run the roles with these tags
    ansible.tags = "install"
  end

end
